services:
  user-service:
    build: ./user-service
    ports: ["3000:3000"]
    networks: ["app-net"]
  product-service:
    build: ./product-service
    ports: ["3001:3001"]
    networks: ["app-net"]
  order-service:
    build: ./order-service  
    ports: ["3002:3002"]
    networks: ["app-net"]
  gateway-service:
    build: ./gateway-service
    ports: ["3003:3003"]
    networks: ["app-net"]
    depends_on:
      - user-service
      - product-service
      - order-service
networks:
  app-net:
